services:
  frontend:
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SUBDOMAIN:-dichtbij3d-tst}.rule=Host(`${SUBDOMAIN:-dichtbij3d-tst}.clovercloud.cc`)"
      - "traefik.http.routers.${SUBDOMAIN:-dichtbij3d-tst}.entrypoints=websecure"
      - "traefik.http.services.${SUBDOMAIN:-dichtbij3d-tst}.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
